### ISSUE TITLE
Include a delay in Acuant calls

### ISSUE THREAD

**Issue by ctro** [18F/identity-loadtest#5]
The IAL2 flow will probably go really fast with the 3rd party calls totally mocked out.
The IdP (or locust?) should be able to include some default delay for `assure_id_results` calls.

**Comment by jgrevich** [comment]
good point, what are you thinking in terms of amount of delay? 100ms or whatever the avg. response time is from accuant?

**Comment by ctro** [comment]
Closing as duplicate of https://github.com/18F/identity-devops/issues/2333
